### ISSUE TITLE
A logo and icon for compare.html

### ISSUE THREAD

**Issue by linadesteem** [tshino/compare#43]
Hi
I am a graphic designer and I want to contribute to this project, I think your project need a logo or at least a icon to put as favicon.

Here I made a simple and modern logo:

![image](https://user-images.githubusercontent.com/35618068/40499392-fb14b612-5fab-11e8-837c-272495a85ede.png)
![image](https://user-images.githubusercontent.com/35618068/40499399-fdbb7edc-5fab-11e8-8eff-43e97ecf8b6a.png)

what do you think? if you like it I will send a PR with svg files.

**Comment by tshino** [comment]
I am glad to have a nice offer.
Seeing your logo and the composition, I realized that putting a logo to my application is really a nice thing.
And that motivated me to create my own version.
I like the idea to make an icon based on the looks of the app.
However your icon does not seem to express the most important aspect of this app, which is visual comparison of two (or more) pictures.
Though I am not sure I can make better one, I try it.
Thank you.

**Comment by linadesteem** [comment]
No problem :)
